// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
<<<<<<< HEAD
import { defineConfig, env } from "prisma/config";
=======
import { defineConfig } from "prisma/config";
>>>>>>> ce037113d509e9985f28ad20e3d581562529f4ee

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
<<<<<<< HEAD
    url: env('DATABASE_URL'),
=======
    url: process.env["DATABASE_URL"],
>>>>>>> ce037113d509e9985f28ad20e3d581562529f4ee
  },
});
